### ISSUE TITLE
Linked data URI for the selected statement gets not applied to the item.

### ISSUE THREAD

**Issue by HistArchivist** [zerocrates/RightsStatements#2]
If the human-readable name is selected from the drop-down menu, no linked data URI for the selected statement gets displayed or applied.

**Comment by zerocrates** [comment]
I'm not sure I understand the problem. Can you show screenshots or something similar for what's happening vs. what you expect?

**Comment by HistArchivist** [comment]
What I expect:
![ValueSuggest-LC-ISO639-2-Languages](https://user-images.githubusercontent.com/48437622/55055207-9ba7e700-5062-11e9-9b9d-182e3eea98f6.png)
like with ValueSuggest: LC: ISO639-2-Languages

What I get:
![RightsStatement](https://user-images.githubusercontent.com/48437622/55054989-f7be3b80-5061-11e9-9d71-e144d27923da.png)
The corresponding linked data URI <http://rightsstatements.org/vocab/InC-EDU/1.0/> is at least not displayed – and applied/stored?

Omeka 1.3.0 with Rights Statements 0.2.0

**Comment by zerocrates** [comment]
The interface there doesn't show the values separately like Value Suggest does, but it is storing both the label and the URI (you can check by looking at the API, or deactivating the plugin temporarily and seeing how the value is displayed).

**Comment by HistArchivist** [comment]
Confirmed. Thanks.
